package github.oaster2000.mcuo.models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

/**
 * ModelPlayer - Either Mojang or a mod author
 * Created using Tabula 7.0.0
 */
public class ModelOwenSuit2 extends ModelBiped {
    public ModelRenderer LogoTop;
    public ModelRenderer LogoCentre;
    public ModelRenderer LogoLeft;
    public ModelRenderer LogoBottom;
    public ModelRenderer LogoRight;
    public ModelRenderer Body;
    public ModelRenderer RightArm;
    public ModelRenderer Head;
    public ModelRenderer LeftLeg;
    public ModelRenderer RightLeg;
    public ModelRenderer LeftArm;
    public ModelRenderer Torso1;
    public ModelRenderer Torso2;
    public ModelRenderer Torso3;
    public ModelRenderer Torso4;
    public ModelRenderer Torso5;
    public ModelRenderer Torso6;
    public ModelRenderer Torso7;
    public ModelRenderer Torso8;
    public ModelRenderer Torso9;
    public ModelRenderer Torso10;
    public ModelRenderer Torso11;
    public ModelRenderer WristBandR4;
    public ModelRenderer WristBandR3;
    public ModelRenderer WristBandR2;
    public ModelRenderer WristBandR1;
    public ModelRenderer ShoulderR;
    public ModelRenderer RightSleeve1;
    public ModelRenderer RightSleeve2;
    public ModelRenderer RightSleeve3;
    public ModelRenderer ShoulderL;
    public ModelRenderer WristBandL1;
    public ModelRenderer WristBandL2;
    public ModelRenderer WristBandL3;
    public ModelRenderer WristBandL4;
    public ModelRenderer LeftSleeve1;
    public ModelRenderer LeftSleeve2;
    public ModelRenderer LeftSleeve3;
    public ModelRenderer LeftSleeve4;

    public ModelOwenSuit2(float expand) {
		super(expand, 0, 96, 64);
        this.LogoRight = new ModelRenderer(this, 82, 5);
        this.LogoRight.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LogoRight.addBox(2.0F, 4.0F, -5.0F, 1, 2, 1, 0.0F);
        this.WristBandR1 = new ModelRenderer(this, 64, 32);
        this.WristBandR1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WristBandR1.addBox(-1.0F, 5.0F, -2.2F, 4, 1, 1, 0.0F);
        this.LeftSleeve3 = new ModelRenderer(this, 57, 35);
        this.LeftSleeve3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LeftSleeve3.addBox(-3.0F, -2.0F, 1.2F, 4, 5, 1, 0.0F);
        this.Torso5 = new ModelRenderer(this, 64, 40);
        this.Torso5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso5.addBox(2.0F, 0.0F, -2.2F, 2, 2, 1, 0.0F);
        this.WristBandL2 = new ModelRenderer(this, 64, 26);
        this.WristBandL2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WristBandL2.addBox(-3.2F, 5.0F, -2.0F, 1, 1, 4, 0.0F);
        this.LeftSleeve2 = new ModelRenderer(this, 57, 35);
        this.LeftSleeve2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LeftSleeve2.addBox(-3.2F, -2.0F, -2.0F, 1, 5, 4, 0.0F);
        this.Torso4 = new ModelRenderer(this, 64, 40);
        this.Torso4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso4.addBox(-4.0F, 0.0F, -2.2F, 2, 2, 1, 0.0F);
        this.WristBandR4 = new ModelRenderer(this, 64, 26);
        this.WristBandR4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WristBandR4.addBox(-1.2F, 5.0F, -2.0F, 1, 1, 4, 0.0F);
        this.RightArm = new ModelRenderer(this, 40, 16);
        this.RightArm.setRotationPoint(5.0F, 2.0F, 0.0F);
        this.RightArm.addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4, 0.0F);
        this.WristBandL4 = new ModelRenderer(this, 64, 26);
        this.WristBandL4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WristBandL4.addBox(0.2F, 5.0F, -2.0F, 1, 1, 4, 0.0F);
        this.Head = new ModelRenderer(this, 0, 0);
        this.Head.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Head.addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8, 0.0F);
        this.Torso8 = new ModelRenderer(this, 64, 40);
        this.Torso8.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso8.addBox(-1.0F, 1.3F, -2.2F, 2, 1, 1, 0.0F);
        this.RightSleeve1 = new ModelRenderer(this, 57, 35);
        this.RightSleeve1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.RightSleeve1.addBox(-1.0F, -2.0F, -2.2F, 4, 5, 1, 0.0F);
        this.RightSleeve2 = new ModelRenderer(this, 57, 35);
        this.RightSleeve2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.RightSleeve2.addBox(2.2F, -2.0F, -2.0F, 1, 5, 4, 0.0F);
        this.WristBandL1 = new ModelRenderer(this, 64, 32);
        this.WristBandL1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WristBandL1.addBox(-3.0F, 5.0F, -2.2F, 4, 1, 1, 0.0F);
        this.Torso11 = new ModelRenderer(this, 64, 35);
        this.Torso11.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso11.addBox(-4.0F, 0.0F, 1.2F, 8, 12, 1, 0.0F);
        this.WristBandL3 = new ModelRenderer(this, 64, 32);
        this.WristBandL3.mirror = true;
        this.WristBandL3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WristBandL3.addBox(-3.0F, 5.0F, 1.2F, 4, 1, 1, 0.0F);
        this.RightSleeve3 = new ModelRenderer(this, 57, 35);
        this.RightSleeve3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.RightSleeve3.addBox(-1.0F, -2.0F, 1.2F, 4, 5, 1, 0.0F);
        this.Torso2 = new ModelRenderer(this, 64, 40);
        this.Torso2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso2.addBox(-2.0F, 1.0F, -2.2F, 3, 1, 1, 0.0F);
        this.setRotateAngle(Torso2, 0.0F, 0.0F, 0.5009094953223726F);
        this.Torso3 = new ModelRenderer(this, 64, 40);
        this.Torso3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso3.addBox(-1.0F, 1.0F, -2.2F, 3, 1, 1, 0.0F);
        this.setRotateAngle(Torso3, 0.0F, 0.0F, -0.5009094953223726F);
        this.LogoLeft = new ModelRenderer(this, 64, 4);
        this.LogoLeft.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LogoLeft.addBox(-3.0F, 4.0F, -5.0F, 1, 2, 1, 0.0F);
        this.LogoTop = new ModelRenderer(this, 72, 0);
        this.LogoTop.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LogoTop.addBox(-1.0F, 2.0F, -5.0F, 2, 1, 1, 0.0F);
        this.Torso10 = new ModelRenderer(this, 64, 35);
        this.Torso10.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso10.addBox(-4.2F, 0.0F, -2.0F, 1, 12, 4, 0.0F);
        this.WristBandR3 = new ModelRenderer(this, 64, 32);
        this.WristBandR3.mirror = true;
        this.WristBandR3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WristBandR3.addBox(-1.0F, 5.0F, 1.2F, 4, 1, 1, 0.0F);
        this.LogoBottom = new ModelRenderer(this, 72, 11);
        this.LogoBottom.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LogoBottom.addBox(-1.0F, 7.0F, -5.0F, 2, 1, 1, 0.0F);
        this.Torso7 = new ModelRenderer(this, 64, 40);
        this.Torso7.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso7.addBox(-2.0F, 1.0F, -2.2F, 1, 1, 1, 0.0F);
        this.LeftSleeve4 = new ModelRenderer(this, 57, 35);
        this.LeftSleeve4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LeftSleeve4.addBox(0.3F, -2.0F, -2.0F, 1, 5, 4, 0.0F);
        this.LogoCentre = new ModelRenderer(this, 70, 4);
        this.LogoCentre.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LogoCentre.addBox(-2.0F, 3.0F, -5.0F, 4, 4, 1, 0.0F);
        this.Body = new ModelRenderer(this, 16, 16);
        this.Body.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Body.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 0.0F);
        this.ShoulderR = new ModelRenderer(this, 64, 15);
        this.ShoulderR.mirror = true;
        this.ShoulderR.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ShoulderR.addBox(-1.0F, -3.0F, -2.5F, 5, 5, 5, 0.0F);
        this.Torso6 = new ModelRenderer(this, 64, 40);
        this.Torso6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso6.addBox(1.0F, 1.0F, -2.2F, 1, 1, 1, 0.0F);
        this.LeftLeg = new ModelRenderer(this, 0, 16);
        this.LeftLeg.setRotationPoint(-1.9F, 12.0F, 0.0F);
        this.LeftLeg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.0F);
        this.RightLeg = new ModelRenderer(this, 0, 16);
        this.RightLeg.setRotationPoint(1.9F, 12.0F, 0.0F);
        this.RightLeg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.0F);
        this.LeftArm = new ModelRenderer(this, 40, 16);
        this.LeftArm.setRotationPoint(-5.0F, 2.0F, 0.0F);
        this.LeftArm.addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4, 0.0F);
        this.Torso1 = new ModelRenderer(this, 64, 35);
        this.Torso1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso1.addBox(-4.0F, 2.0F, -2.2F, 8, 10, 1, 0.0F);
        this.WristBandR2 = new ModelRenderer(this, 64, 26);
        this.WristBandR2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WristBandR2.addBox(2.2F, 5.0F, -2.0F, 1, 1, 4, 0.0F);
        this.Torso9 = new ModelRenderer(this, 64, 35);
        this.Torso9.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Torso9.addBox(3.2F, 0.0F, -2.0F, 1, 12, 4, 0.0F);
        this.ShoulderL = new ModelRenderer(this, 64, 15);
        this.ShoulderL.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ShoulderL.addBox(-4.0F, -3.0F, -2.5F, 5, 5, 5, 0.0F);
        this.LeftSleeve1 = new ModelRenderer(this, 57, 35);
        this.LeftSleeve1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LeftSleeve1.addBox(-3.0F, -2.0F, -2.2F, 4, 5, 1, 0.0F);
        
        this.bipedLeftArm.addChild(WristBandR1);
        this.bipedLeftArm.addChild(WristBandR2);
        this.bipedLeftArm.addChild(WristBandR3);
        this.bipedLeftArm.addChild(WristBandR4);
        this.bipedLeftArm.addChild(ShoulderR);
        this.bipedLeftArm.addChild(this.RightSleeve1);
        this.bipedLeftArm.addChild(this.RightSleeve2);
        this.bipedLeftArm.addChild(this.RightSleeve3);
        
        this.bipedRightArm.addChild(WristBandL1);
        this.bipedRightArm.addChild(WristBandL2);
        this.bipedRightArm.addChild(WristBandL3);
        this.bipedRightArm.addChild(WristBandL4);
        this.bipedRightArm.addChild(ShoulderL);
        this.bipedRightArm.addChild(this.LeftSleeve3);
        this.bipedRightArm.addChild(this.LeftSleeve2);
        this.bipedRightArm.addChild(this.LeftSleeve4);
        this.bipedRightArm.addChild(this.LeftSleeve1);
        
        this.bipedBody.addChild(this.Torso5);
        this.bipedBody.addChild(this.Torso4);
        this.bipedBody.addChild(this.Torso8);
        this.bipedBody.addChild(this.Torso11);
        this.bipedBody.addChild(this.Torso2);
        this.bipedBody.addChild(this.Torso3);
        this.bipedBody.addChild(this.Torso10);
        this.bipedBody.addChild(this.Torso7);
        this.bipedBody.addChild(this.Torso6);
        this.bipedBody.addChild(this.Torso1);
        this.bipedBody.addChild(this.Torso9);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
    	super.render(entity, f, f1, f2, f3, f4, f5);
    	this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.LogoRight.offsetX, this.LogoRight.offsetY, this.LogoRight.offsetZ);
        GlStateManager.translate(this.LogoRight.rotationPointX * f5, this.LogoRight.rotationPointY * f5, this.LogoRight.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.5D);
        GlStateManager.translate(-this.LogoRight.offsetX, -this.LogoRight.offsetY, -this.LogoRight.offsetZ);
        GlStateManager.translate(-this.LogoRight.rotationPointX * f5, -this.LogoRight.rotationPointY * f5, -this.LogoRight.rotationPointZ * f5);
        this.LogoRight.render(f5);
        GlStateManager.popMatrix();
        this.RightArm.render(f5);
        this.Head.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.LogoLeft.offsetX, this.LogoLeft.offsetY, this.LogoLeft.offsetZ);
        GlStateManager.translate(this.LogoLeft.rotationPointX * f5, this.LogoLeft.rotationPointY * f5, this.LogoLeft.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.5D);
        GlStateManager.translate(-this.LogoLeft.offsetX, -this.LogoLeft.offsetY, -this.LogoLeft.offsetZ);
        GlStateManager.translate(-this.LogoLeft.rotationPointX * f5, -this.LogoLeft.rotationPointY * f5, -this.LogoLeft.rotationPointZ * f5);
        this.LogoLeft.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.LogoTop.offsetX, this.LogoTop.offsetY, this.LogoTop.offsetZ);
        GlStateManager.translate(this.LogoTop.rotationPointX * f5, this.LogoTop.rotationPointY * f5, this.LogoTop.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.5D);
        GlStateManager.translate(-this.LogoTop.offsetX, -this.LogoTop.offsetY, -this.LogoTop.offsetZ);
        GlStateManager.translate(-this.LogoTop.rotationPointX * f5, -this.LogoTop.rotationPointY * f5, -this.LogoTop.rotationPointZ * f5);
        this.LogoTop.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.LogoBottom.offsetX, this.LogoBottom.offsetY, this.LogoBottom.offsetZ);
        GlStateManager.translate(this.LogoBottom.rotationPointX * f5, this.LogoBottom.rotationPointY * f5, this.LogoBottom.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.5D);
        GlStateManager.translate(-this.LogoBottom.offsetX, -this.LogoBottom.offsetY, -this.LogoBottom.offsetZ);
        GlStateManager.translate(-this.LogoBottom.rotationPointX * f5, -this.LogoBottom.rotationPointY * f5, -this.LogoBottom.rotationPointZ * f5);
        this.LogoBottom.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.LogoCentre.offsetX, this.LogoCentre.offsetY, this.LogoCentre.offsetZ);
        GlStateManager.translate(this.LogoCentre.rotationPointX * f5, this.LogoCentre.rotationPointY * f5, this.LogoCentre.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.5D);
        GlStateManager.translate(-this.LogoCentre.offsetX, -this.LogoCentre.offsetY, -this.LogoCentre.offsetZ);
        GlStateManager.translate(-this.LogoCentre.rotationPointX * f5, -this.LogoCentre.rotationPointY * f5, -this.LogoCentre.rotationPointZ * f5);
        this.LogoCentre.render(f5);
        GlStateManager.popMatrix();
        this.Body.render(f5);
        this.LeftLeg.render(f5);
        this.RightLeg.render(f5);
        this.LeftArm.render(f5);
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
